os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '10'
  - 'node'
jobs:
  include:
    - stage: Check Coverage
      node_js: node
      script: tap --coverage-report=text-lcov | coveralls && rm -rf ./coverage
